### ISSUE TITLE
Uploading gifs doesn't work

### ISSUE THREAD

**Issue by sarayourfriend** [SeattleDSA/OpenOversight#29]
Steps to reproduce:
1. Upload a gif
2. `dc logs -f web`
3. Note the error:

```
web_1           | Traceback (most recent call last):
web_1           |   File "/usr/local/lib/python3.9/site-packages/flask/app.py", line 2309, in __call__
web_1           |     return self.wsgi_app(environ, start_response)
web_1           |   File "/usr/local/lib/python3.9/site-packages/flask/app.py", line 2295, in wsgi_app
web_1           |     response = self.handle_exception(e)
web_1           |   File "/usr/local/lib/python3.9/site-packages/flask/app.py", line 1741, in handle_exception
web_1           |     reraise(exc_type, exc_value, tb)
web_1           |   File "/usr/local/lib/python3.9/site-packages/flask/_compat.py", line 35, in reraise
web_1           |     raise value
web_1           |   File "/usr/local/lib/python3.9/site-packages/flask/app.py", line 2292, in wsgi_app
web_1           |     response = self.full_dispatch_request()
web_1           |   File "/usr/local/lib/python3.9/site-packages/flask/app.py", line 1815, in full_dispatch_request
web_1           |     rv = self.handle_user_exception(e)
web_1           |   File "/usr/local/lib/python3.9/site-packages/flask/app.py", line 1718, in handle_user_exception
web_1           |     reraise(exc_type, exc_value, tb)
web_1           |   File "/usr/local/lib/python3.9/site-packages/flask/_compat.py", line 35, in reraise
web_1           |     raise value
web_1           |   File "/usr/local/lib/python3.9/site-packages/flask/app.py", line 1813, in full_dispatch_request
web_1           |     rv = self.dispatch_request()
web_1           |   File "/usr/local/lib/python3.9/site-packages/flask/app.py", line 1799, in dispatch_request
web_1           |     return self.view_functions[rule.endpoint](**req.view_args)
web_1           |   File "/usr/local/lib/python3.9/site-packages/flask_limiter/extension.py", line 544, in __inner
web_1           |     return obj(*a, **k)
web_1           |   File "/usr/src/app/OpenOversight/app/main/views.py", line 1090, in upload
web_1           |     image = upload_image_to_s3_and_store_in_db(file_to_upload, current_user.get_id(), department_id=department_id)
web_1           |   File "/usr/src/app/OpenOversight/app/utils.py", line 526, in upload_image_to_s3_and_store_in_db
web_1           |     date_taken = find_date_taken(pimage)
web_1           |   File "/usr/src/app/OpenOversight/app/utils.py", line 562, in find_date_taken
web_1           |     if pimage._getexif():
web_1           | AttributeError: 'GifImageFile' object has no attribute '_getexif'
```

Expected behavior:
A sensible error should be shown if we don't support gifs. Otherwise we can skip finding the date taken when it fails?

**Comment by sarayourfriend** [comment]
Closed by #32
